'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { db } = require('../core/db');
const config = require('../config');
const { createLogger } = require('../core/logger');
const { normalize } = require('../knowledge/store');

const log = createLogger('skills');

const slugify = (s) =>
  normalize(s)
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 60) || `skill-${Date.now()}`;

/**
 * Find an existing auto-generated skill that covers the same ground.
 *
 * Each training run names topics slightly differently ("Sayt ochilmayapti" vs
 * "Sayt ochilmayapti / xato"), which would otherwise pile up near-duplicate
 * skills that all fire at once and bloat the prompt. Matching on trigger
 * overlap catches those regardless of wording.
 */
function findDuplicate(slug, name, triggers) {
  const incoming = new Set(
    String(triggers || '')
      .split(/[,\n]/)
      .map((t) => normalize(t))
      .filter((t) => t.length >= 3)
  );
  if (!incoming.size) return null;

  const nName = normalize(name);
  for (const s of db.prepare('SELECT * FROM skills WHERE auto_generated = 1').all()) {
    if (s.slug === slug) continue;
    if (normalize(s.name) === nName) return s;

    const existing = new Set(
      String(s.triggers || '')
        .split(/[,\n]/)
        .map((t) => normalize(t))
        .filter((t) => t.length >= 3)
    );
    if (!existing.size) continue;

    let shared = 0;
    for (const t of incoming) if (existing.has(t)) shared++;
    const overlap = shared / Math.min(incoming.size, existing.size);
    if (overlap >= 0.55) return s;
  }
  return null;
}

/** Persist a skill to the DB and mirror it to data/skills/<slug>.md for review. */
function save({ slug, name, description = '', triggers = '', instructions, examples = '', priority = 100, autoGenerated = 1, enabled = 1, dedupe = false }) {
  let s = slug || slugify(name);
  let existing = db.prepare('SELECT id, version FROM skills WHERE slug = ?').get(s);

  // Generated skills fold into an equivalent existing one instead of piling up.
  if (!existing && dedupe) {
    const dup = findDuplicate(s, name, triggers);
    if (dup) {
      log.info('Takroriy koʻnikma birlashtirildi', { incoming: s, into: dup.slug });
      s = dup.slug;
      existing = dup;
    }
  }

  if (existing) {
    db.prepare(
      `UPDATE skills SET name = ?, description = ?, triggers = ?, instructions = ?, examples = ?,
       priority = ?, enabled = ?, version = version + 1, updated_at = datetime('now') WHERE slug = ?`
    ).run(name, description, triggers, instructions, examples, priority, enabled, s);
  } else {
    db.prepare(
      `INSERT INTO skills (slug, name, description, triggers, instructions, examples, priority, enabled, auto_generated)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(s, name, description, triggers, instructions, examples, priority, enabled, autoGenerated);
  }

  writeFile({ slug: s, name, description, triggers, instructions, examples, priority });
  return s;
}

function writeFile(skill) {
  try {
    const md = `---
slug: ${skill.slug}
name: ${skill.name}
priority: ${skill.priority}
triggers: ${skill.triggers}
---

# ${skill.name}

${skill.description || ''}

## Ko'rsatma
${skill.instructions}

${skill.examples ? `## Namunalar\n${skill.examples}\n` : ''}`;
    fs.writeFileSync(path.join(config.skillsDir, `${skill.slug}.md`), md, 'utf8');
  } catch (err) {
    log.warn('skill file write failed', { slug: skill.slug, error: err.message });
  }
}

function list({ includeDisabled = true } = {}) {
  const sql = includeDisabled
    ? 'SELECT * FROM skills ORDER BY priority ASC, id ASC'
    : 'SELECT * FROM skills WHERE enabled = 1 ORDER BY priority ASC, id ASC';
  return db.prepare(sql).all();
}

const get = (slug) => db.prepare('SELECT * FROM skills WHERE slug = ?').get(slug);
const remove = (slug) => {
  db.prepare('DELETE FROM skills WHERE slug = ?').run(slug);
  try {
    fs.unlinkSync(path.join(config.skillsDir, `${slug}.md`));
  } catch {
    /* file may not exist */
  }
};
const setEnabled = (slug, on) => db.prepare('UPDATE skills SET enabled = ? WHERE slug = ?').run(on ? 1 : 0, slug).changes;

/**
 * Pick the skills relevant to an incoming message.
 * Scoring: exact trigger phrase > single trigger word > name/description match.
 * Priority breaks ties so critical skills (policy, escalation) always surface.
 */
function match(text, limit = 3) {
  const hay = ' ' + normalize(text) + ' ';
  const scored = [];

  for (const sk of list({ includeDisabled: false })) {
    let score = 0;
    const triggers = String(sk.triggers || '')
      .split(/[,\n]/)
      .map((t) => normalize(t))
      .filter((t) => t.length >= 2);

    for (const t of triggers) {
      if (!t) continue;
      if (t.includes(' ')) {
        if (hay.includes(t)) score += 3;
      } else if (hay.includes(' ' + t + ' ') || hay.includes(' ' + t)) {
        score += 2;
      }
    }
    const nd = normalize(`${sk.name} ${sk.description}`);
    for (const w of nd.split(' ')) if (w.length > 4 && hay.includes(w)) score += 0.5;

    if (sk.priority <= 10) score += 1.5; // always-on skills get a nudge
    if (score > 0) scored.push({ ...sk, score });
  }

  return scored
    .sort((a, b) => b.score - a.score || a.priority - b.priority)
    .slice(0, limit);
}

/** Always-on skills (priority <= 5) are injected regardless of the message. */
function alwaysOn() {
  return db.prepare('SELECT * FROM skills WHERE enabled = 1 AND priority <= 5 ORDER BY priority ASC').all();
}

function selectFor(text, limit = 3) {
  const on = alwaysOn();
  const matched = match(text, limit).filter((m) => !on.some((o) => o.slug === m.slug));
  return [...on, ...matched].slice(0, limit + on.length);
}

/**
 * Curated baseline skills. Any that are missing get (re)installed — so a
 * deleted or never-created policy skill comes back on the next boot, while
 * existing ones (including operator edits) are left untouched.
 */
function ensureBaseSkills() {
  const base = [
    {
      slug: 'launch-date-policy',
      name: 'Reliz sanasi siyosati',
      description: "Ishga tushish sanasi so'ralganda maxfiylikni saqlash",
      triggers: 'qachon, qacon, kachon, ishga tushadi, ochiladi, reliz, release, launch, chiqadi, sana, когда, when',
      priority: 1,
      instructions:
        "Foydalanuvchi ANITOKU qachon ishga tushishini so'rasa — ANIQ SANA, OY yoki YIL aytma, taxmin ham qilma. \"Juda tez orada\" degan ma'noda javob ber, kutayotgani uchun minnatdorchilik bildir va rasmiy kanalni (@anitoku) kuzatib borishni tavsiya qil. Javobni har safar boshqacha so'zlar bilan yoz — shablon takrorlanmasin.",
      examples:
        "U: Sayt qachon ochiladi?\nS: Aniq sanani hozircha oshkor qilmayapmiz 🙂 Lekin ishoning, juda oz qoldi! E'lon birinchi bo'lib @anitoku kanalida chiqadi — o'tkazib yubormang.",
      autoGenerated: 0,
    },
    {
      slug: 'platform-info',
      name: 'Platforma imkoniyatlari',
      description: 'ANITOKU nima qila oladi degan savollar',
      triggers: "nima, nimaga, imkoniyat, funksiya, qanday ishlaydi, manga, anime, ko'rish, o'qish, reyting, profil, do'kon, missiya",
      priority: 20,
      instructions:
        "Platforma imkoniyatlarini qisqa va jozibali qilib tushuntir: o'zbek tilidagi sifatli anime va manga, aqlli qidiruv, har bir anime uchun sahifa, 10 ballik reyting, profil bezaklari va ramkalar, missiyalar va yutuqlar, do'kon, yangiliklar, community, AI botlar, veb va mobil. Hammasini bir xabarda sanab tashlama — foydalanuvchi nimaga qiziqqan bo'lsa, o'shanga urg'u ber.",
      autoGenerated: 0,
    },
    {
      slug: 'join-team',
      name: 'Jamoaga qabul',
      description: "Ovoz aktyorligi, tarjima, montaj bo'yicha murojaatlar",
      triggers: "ishlamoqchi, ish, vakansiya, jamoa, ovoz, aktyor, dubbing, tarjimon, montaj, dayber, qo'shilmoqchi",
      priority: 25,
      instructions:
        "Nomzodni iliq kutib ol. Ochiq yo'nalishlar: ovoz aktyor(ka)lari, montajyorlar, dayberlar, tarjimonlar. Qaysi yo'nalish qiziqtirishini so'ra va namuna ish (ovoz yozuvi yoki tarjima parchasi) so'ra. Yakuniy qaror uchun @anitoku_admin ga yo'naltir.",
      autoGenerated: 0,
    },
    {
      slug: 'bug-report',
      name: 'Texnik muammo',
      description: 'Sayt/ilova ishlamayotgani haqidagi shikoyatlar',
      triggers: "ishlamayapti, ochilmayapti, xato, error, muammo, bug, sekin, yuklanmayapti, kirolmayapman",
      priority: 15,
      instructions:
        "Muammo uchun uzr so'ra, keyin aniq diagnostika ma'lumotini so'ra: qurilma va brauzer, qanday xato xabari chiqmoqda, skrinshot. Ma'lumot to'liq bo'lsa — texnik jamoaga uzatilishini ayt va escalate_to_human vositasidan foydalan.",
      autoGenerated: 0,
    },
    {
      slug: 'greeting',
      name: 'Salomlashish',
      description: 'Birinchi kontakt va salomlashuv',
      triggers: 'salom, assalom, hi, hello, привет, qalesan, yaxshimisiz, start',
      priority: 40,
      instructions:
        "Qisqa va iliq salomlash. O'zingni tanishtir (ANITOKU qo'llab-quvvatlash xizmati) va qanday yordam bera olishingni so'ra. Uzun kirish matni yozma — bitta-ikkita jumla kifoya.",
      autoGenerated: 0,
    },
  ];

  const installed = [];
  for (const s of base) {
    if (get(s.slug)) continue; // already present — never clobber existing content
    save(s);
    installed.push(s.slug);
  }
  if (installed.length) log.info('Base skills installed', { count: installed.length, slugs: installed });
  return installed.length;
}

/**
 * Fold near-duplicate auto-generated skills into one another.
 *
 * Dedupe on write only protects new skills; runs made before it existed (or
 * topics that drifted apart over several runs) still leave overlapping skills
 * that all fire together and crowd the prompt. This sweeps the whole table and
 * is safe to run repeatedly — curated skills are never touched, and a
 * generated skill overlapping a curated one is dropped in the curated one's
 * favour.
 */
function consolidate() {
  const merged = [];
  const kept = [];

  const triggerSet = (s) =>
    new Set(
      String(s.triggers || '')
        .split(/[,\n]/)
        .map((t) => normalize(t))
        .filter((t) => t.length >= 3)
    );

  const overlap = (a, b) => {
    if (!a.size || !b.size) return 0;
    let shared = 0;
    for (const t of a) if (b.has(t)) shared++;
    return shared / Math.min(a.size, b.size);
  };

  // Curated skills win every conflict, so seed the keep-list with them.
  const curated = db.prepare('SELECT * FROM skills WHERE auto_generated = 0').all();
  for (const c of curated) kept.push({ skill: c, triggers: triggerSet(c), curated: true });

  const autos = db.prepare('SELECT * FROM skills WHERE auto_generated = 1 ORDER BY priority ASC, id ASC').all();
  for (const s of autos) {
    const ts = triggerSet(s);
    const hit = kept.find((k) => overlap(ts, k.triggers) >= 0.55 || normalize(k.skill.name) === normalize(s.name));

    if (!hit) {
      kept.push({ skill: s, triggers: ts, curated: false });
      continue;
    }

    if (hit.curated) {
      // A curated skill already covers this ground — drop the generated copy.
      remove(s.slug);
      merged.push({ dropped: s.slug, into: hit.skill.slug, reason: 'curated' });
      continue;
    }

    // Merge trigger vocabularies so the survivor still matches both wordings.
    const union = [...new Set([...hit.triggers, ...ts])].join(', ');
    db.prepare("UPDATE skills SET triggers = ?, updated_at = datetime('now') WHERE slug = ?").run(union, hit.skill.slug);
    hit.triggers = triggerSet({ triggers: union });
    remove(s.slug);
    merged.push({ dropped: s.slug, into: hit.skill.slug, reason: 'overlap' });
  }

  if (merged.length) log.info('Koʻnikmalar konsolidatsiya qilindi', { merged: merged.length, detail: merged });
  return { merged: merged.length, remaining: db.prepare('SELECT COUNT(*) AS c FROM skills').get().c, detail: merged };
}

module.exports = { save, list, get, remove, setEnabled, match, selectFor, alwaysOn, ensureBaseSkills, slugify, consolidate };
